### ISSUE TITLE
Phedex transfer

### ISSUE THREAD

**Issue by steggema** [CERN-PH-CMG/cmg-cmssw#35]
Hi Sezen,

Would it be possible to transfer the following samples?

/TT_Tune4C_13TeV-pythia8-tauola/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW
/DYJetsToLL_M-50_13TeV-pythia6/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW

The request is a bit unusual as these are GEN-SIM-RAW samples, but the samples aren't particularly large.

Thanks,
Jan

**Comment by ssekmen** [comment]
Hello Jan,
I requested the samples:
https://cmsweb.cern.ch/phedex/prod/Request::View?request=411445
Sezen

**Comment by ssekmen** [comment]
Hi all,
We need to make space in the buffer.
Anyone still using 
0.0  /WmWmqq_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM 
0.0  /WpWpqq_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM 
0.1  /TBZToLL_4F_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM 
1.6  /DYJetsToLL_M-50_13TeV-pythia6/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW 
1.8  /RelValPYTHIA6_Tauola_TTbar_TuneZ2star_8TeV/CMSSW_7_0_0_pre8-PU_PRE_ST62_V8_egValid-v1/GEN-SIM-RECO 
6.4  /TT_Tune4C_13TeV-pythia8-tauola/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW 
9.0  /JPsiToMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/Fall11-PU_S6_START44_V9B-v1/AODSIM

**Comment by ssekmen** [comment]
I try messaging again:

We need to make space in the buffer.  Please tell me if anyone is still using the following samples until tomorrow - otherwise I will remove them.

0.0  /WmWmqq_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM 
0.0  /WpWpqq_8TeV-madgraph/Summer12_DR53X-PU_S10_START53_V7A-v1/AODSIM 
0.1  /TBZToLL_4F_TuneZ2star_8TeV-madgraph-tauola/Summer12_DR53X-PU_S10_START53_V7C-v1/AODSIM 
1.6  /DYJetsToLL_M-50_13TeV-pythia6/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW 
1.8  /RelValPYTHIA6_Tauola_TTbar_TuneZ2star_8TeV/CMSSW_7_0_0_pre8-PU_PRE_ST62_V8_egValid-v1/GEN-SIM-RECO 
6.4  /TT_Tune4C_13TeV-pythia8-tauola/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW 
9.0  /JPsiToMuMu_2MuPEtaFilter_7TeV-pythia6-evtgen/Fall11-PU_S6_START44_V9B-v1/AODSIM 

Thanks.
Sezen

**Comment by steggema** [comment]
Hi Sezen,

I still need 

/DYJetsToLL_M-50_13TeV-pythia6/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW 
/TT_Tune4C_13TeV-pythia8-tauola/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW 

Thanks,
Jan

**Comment by gpetruc** [comment]
Hi Sezen,

WpWpqq, WmWmqq and TBZ can be deleted (though that won't solve the space
issue)

```
Giovanni
```

Il 1-apr-2014 14:51 "ssekmen" notifications@github.com ha scritto:

**Comment by ssekmen** [comment]
OK, thanks for the quick reply Jan.
Please let me know when I can remove them.
Markus needs to transfer some samples a bit urgently.
cheers,
Sezen

**Comment by gpetruc** [comment]
Can the samples be copied over to regular eos space to free the buffer?

```
Giovanni
```

Il 1-apr-2014 14:54 "steggema" notifications@github.com ha scritto:

**Comment by ssekmen** [comment]
Thanks Giovanni.
Unfortunately I don't know a straightforward way to transfer from the buffer to eos - though there must be a way.  Anyone know this?
in any case, let's see how much time Jan needs for his samples first.
Sezen

**Comment by steggema** [comment]
I guess I'll need them for another week. I'd be happy to redirect the jobs and run on them on eos if it's possible to copy them there.

Jan

**Comment by ssekmen** [comment]
Thanks Jan.
We're looking for other possibilities - if things get difficult,we'll get back to you.
Sezen

**Comment by steggema** [comment]
Hi Sezen,

You can remove the ttbar sample (/TT_Tune4C_13TeV-pythia8-tauola/Fall13dr-tsg_PU40bx25_POSTLS162_V2-v1/GEN-SIM-RAW), which should be the main consumer of space.

Thanks,
Jan
