### ISSUE TITLE
Archival of obsolete CMGTuples

### ISSUE THREAD

**Issue by gpetruc** [CERN-PH-CMG/cmg-cmssw#51]
I'm adding a task here so that we can keep a log of what is to be archived and of what has been archived and can be deleted.

To my knowledge @gitytakahas has already started archiving V5.6 (8TeV only), V5.8, V5.9, V5.10, V5.12, V5.13 and V5.14, but I don't  know if the archival is complete and if the integrity of the copy has been checked (i.e. that all files have been successfully copied and none is corrupted)

Of these, I'd ask to keep on eos V5.10 for another few weeks as we're still using it for a few susy fake rate studies, though as soon as we'll be done producing the PFAOD and V5.18 CMGTuples of the QCD samples in the buffer then for us V5.10 can go too.

**Comment by gitytakahas** [comment]
Hi Giovanni, all,

I have started archiving for those samples listed in the twiki [1] since last Friday.
The location of these samples on the castor is : 

/castor/cern.ch/cms/archive/user/c/cmgtools/May2014/[with_same_datasetname_in_eos]

You can check these samples (if you want) by using nsls -l /castor/[path_to_the_file]

I am still copying these samples (In total, there are 140TB to be archived) and plan to finish within this week. Once the archiving will be finished, I will check the integrity of them.
More news later this week.

[1] 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/CMGDeletionMay2014#To_be_considered_for_deletion_po

**Comment by gitytakahas** [comment]
I have finished to archive all the files listed in 

https://twiki.cern.ch/twiki/bin/viewauth/CMS/CMGDeletionMay2014#To_be_considered_for_deletion_po

I am now checking the integrity (# of runs, # of lumis, # of events, # bytes).
The plan is to finish before Wednesday, and start deleting these samples.
If you found any problems, please let me know before then.

cheers, Yuta

**Comment by gitytakahas** [comment]
Dear all,

I have finished to archive all the datasets listed in [1] in the eos user space (in total, 137TB). 
The archived directory on the castor is here.

/castor/cern.ch/cms/archive/user/c/cmgtools/May2014/[with_same_dataset_name_in_eos]

You can see these samples by using 

nsls -l /castor/cern.ch/cms/archive/user/c/cmgtools/May2014/[path_to_the_file].

The original files in eos are on their way to be deleted once their integrities are checked.
So far, 70% of the datasets have been already deleted.

Given the fact that we were at 97% of our group space,
I have asked Giovanni Franzoni / Gianluca to transfer 50TB of the user space to the group space as we have plenty space left in the user space due to this archival campaign. This operation has been already done yesterday [2]. The resulting quota (only the relevant one) is,

> /eos/cms/store/cmst3/user/    520.00 (available)  397.87 (used)  76.51%
> /eos/cms/store/cmst3/group/    518.00 (available)  458.71 (used)  88.55% 

The current space allocation can be found in [3]. 
If you need to access the archived file in the future, you can see the instructions at [4]. 

[1]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/CMGDeletionMay2014#To_be_considered_for_deletion_po

[2]
https://its.cern.ch/jira/browse/CMSCERNTTH-51

[3]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/CERNCMST3#Quota_monitoring

[4]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsCERNArchive

Please let me know if you have any trouble, problems.
Cheers,
Yuta

**Comment by gitytakahas** [comment]
> The original files in eos are on their way to be deleted once their integrities are checked.

All the files are now deleted. 
The quota of the user space has now become,

> /eos/cms/store/cmst3/user/ 520.00 (available) 340 (used) 65.1%

I close this item.

Regards,
Yuta
